### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by wesleytodd**
Added support for shadow dom clicks and fixed the same origin check.

### CODE REVIEW

**Comment by jaafit** [comment]
I copied the isInternal RegExp from this PR to override the sameOrigin check and it seems to work better (whereas previously, every link was considered as same origin).

**Comment by wesleytodd** [comment]
Wow I totally forgot I had staged a release for this and never went through with it! Just to make sure I understand your comment, you tested this change and it is *good*? So I should release this new version?

**Comment by jaafit** [comment]
I only tested the new RegExp.  Not the whole change.  But the new RegExp is definitely better.

**Comment by wesleytodd** [comment]
Cool, then let me merge and release this. Thanks for the help!

**Comment by wesleytodd** [comment]
Published as 1.1.0.

**Pull request closed without merging**
